#!/bin/bash
set -o nounset
set -o errexit

REMOTE=connor@130.95.16.147

rsync -av ~/.vimrc $REMOTE:~/.vimrc 
rsync -av ~/.tmux.conf $REMOTE:~/.tmux.conf 
rsync -av ~/.config/ranger/rc.conf $REMOTE:~/.config/ranger/rc.conf 
